Repository DeuxHuitHuit/craft-template, pull requests merged in 2020-10, with the labels that each got.

#4 fixed php version for cli
  craft
Labels: hacktoberfest-accepted

#6 Normalize boolean params and avoid conflict with loop
  templates/_lib/animation.twig
  templates/_lib/embed-video.twig
  templates/_lib/video.twig
Labels: hacktoberfest-accepted

#7 Prevent image upscaling in config
  config/general.php
Labels: hacktoberfest-accepted

#8 CONFIG - transformGifs : False
  config/general.php
Labels: hacktoberfest-accepted

#9 added all language attrs by default
  templates/_masters/html.twig
Labels: hacktoberfest-accepted

#10 Added language redirect and removed scafolder comments
  config/app.php
  modules/build/config/app.php
  modules/build/src/Build.php
  modules/build/src/variables/BuildVariables.php
  modules/languageRedirect/src/LanguageRedirect.php
Labels: hacktoberfest-accepted

#13 Added html and attributes for new framework compat
  templates/_masters/page.twig
Labels: hacktoberfest-accepted

#14 Add font filenames array as build variable
  modules/build/src/variables/BuildVariables.php
  templates/_masters/fonts.twig
  templates/_masters/html.twig
Labels: enhancement

#19 Add a jshint config
  .jshintrc
Labels: enhancement, hacktoberfest-accepted

#17 Better tailwind config
  tailwind.config.js
Labels: enhancement, hacktoberfest-accepted
